language: node_js
node_js:
    - "10"
addons:
  apt:
    packages:
      - libgconf-2-4

cache:
    npm: true
    directories:
        - node_modules
        - ~/.cache

install:
    - npm ci
    - npm run pretest

script:
    - npm run cy:ci